version: false
compound: false
show-links: false
show-null: true
type-restriction: true
attribute-restriction: false
empty-is-null: true
page-size: 0
page-limit: 20000
request-company-schema: false
request-sharded-schema: false
request-accounting-schema: false
request-accounting-prefix: false
pg-order-by: "created_at"
pg-search_path: '"$user", request-sharded-schema, public'
