CREATE TABLE currency_map (
    key VARCHAR(3),
    symbol VARCHAR(4),
    name TEXT,
    symbol_native VARCHAR(5),
    decimal_digits INT,
    rounding NUMERIC(3, 2),
    code VARCHAR(3),
    name_plural TEXT
);
INSERT INTO currency_map VALUES ('AED','AED','United Arab Emirates Dirham','د.إ.‏',2,0.0,'AED','UAE dirhams');
INSERT INTO currency_map VALUES ('AFN','AFN','Afghan Afghani','؋',0,0.0,'AFN','Afghan Afghanis');
INSERT INTO currency_map VALUES ('ALL','ALL','Albanian Lek','Lek',0,0.0,'ALL','Albanian lekë');
INSERT INTO currency_map VALUES ('AMD','AMD','Armenian Dram','դր.',0,0.0,'AMD','Armenian drams');
INSERT INTO currency_map VALUES ('AOA','AOA','Angolan Kwanza','Kz',2,0.0,'AOA','Angolan kwanzas');
INSERT INTO currency_map VALUES ('ARS','ARS','Argentine Peso','$',2,0.0,'ARS','Argentine pesos');
INSERT INTO currency_map VALUES ('AUD','AU$','Australian Dollar','$',2,0.0,'AUD','Australian dollars');
INSERT INTO currency_map VALUES ('AWG','AWG','Aruban Florin','Afl.',2,0.0,'AWG','Aruban florin');
INSERT INTO currency_map VALUES ('AZN','AZN','Azerbaijani Manat','ман.',2,0.0,'AZN','Azerbaijani manats');
INSERT INTO currency_map VALUES ('BAM','BAM','Bosnia-Herzegovina Convertible Mark','KM',2,0.0,'BAM','Bosnia-Herzegovina convertible marks');
INSERT INTO currency_map VALUES ('BBD','BBD','Barbadian Dollar','$',2,0.0,'BBD','Barbadian dollars');
INSERT INTO currency_map VALUES ('BDT','BDT','Bangladeshi Taka','৳',2,0.0,'BDT','Bangladeshi takas');
INSERT INTO currency_map VALUES ('BGN','BGN','Bulgarian Lev','лв.',2,0.0,'BGN','Bulgarian leva');
INSERT INTO currency_map VALUES ('BHD','BHD','Bahraini Dinar','د.ب.‏',3,0.0,'BHD','Bahraini dinars');
INSERT INTO currency_map VALUES ('BIF','BIF','Burundian Franc','FBu',0,0.0,'BIF','Burundian francs');
INSERT INTO currency_map VALUES ('BMD','BMD','Bermudan Dollar','$',2,0.0,'BMD','Bermudan dollars');
INSERT INTO currency_map VALUES ('BND','BND','Brunei Dollar','$',2,0.0,'BND','Brunei dollars');
INSERT INTO currency_map VALUES ('BOB','BOB','Bolivian Boliviano','Bs',2,0.0,'BOB','Bolivian bolivianos');
INSERT INTO currency_map VALUES ('BRL','R$','Brazilian Real','R$',2,0.0,'BRL','Brazilian reals');
INSERT INTO currency_map VALUES ('BWP','BWP','Botswanan Pula','P',2,0.0,'BWP','Botswanan pulas');
INSERT INTO currency_map VALUES ('BYR','BYR','Belarusian Ruble','BYR',0,0.0,'BYR','Belarusian rubles');
INSERT INTO currency_map VALUES ('BZD','BZD','Belize Dollar','$',2,0.0,'BZD','Belize dollars');
INSERT INTO currency_map VALUES ('CAD','CA$','Canadian Dollar','$',2,0.0,'CAD','Canadian dollars');
INSERT INTO currency_map VALUES ('CDF','CDF','Congolese Franc','FrCD',2,0.0,'CDF','Congolese francs');
INSERT INTO currency_map VALUES ('CHF','CHF','Swiss Franc','CHF',2,0.05,'CHF','Swiss francs');
INSERT INTO currency_map VALUES ('CLP','CLP','Chilean Peso','$',0,0.0,'CLP','Chilean pesos');
INSERT INTO currency_map VALUES ('CNY','CN¥','Chinese Yuan','CN¥',2,0.0,'CNY','Chinese yuan');
INSERT INTO currency_map VALUES ('COP','COP','Colombian Peso','$',0,0.0,'COP','Colombian pesos');
INSERT INTO currency_map VALUES ('CRC','CRC','Costa Rican Colón','₡',0,0.0,'CRC','Costa Rican colóns');
INSERT INTO currency_map VALUES ('CVE','CVE','Cape Verdean Escudo','CVE',2,0.0,'CVE','Cape Verdean escudos');
INSERT INTO currency_map VALUES ('CZK','CZK','Czech Republic Koruna','Kč',2,0.0,'CZK','Czech Republic korunas');
INSERT INTO currency_map VALUES ('DJF','DJF','Djiboutian Franc','Fdj',0,0.0,'DJF','Djiboutian francs');
INSERT INTO currency_map VALUES ('DKK','DKK','Danish Krone','kr',2,0.0,'DKK','Danish kroner');
INSERT INTO currency_map VALUES ('DOP','DOP','Dominican Peso','$',2,0.0,'DOP','Dominican pesos');
INSERT INTO currency_map VALUES ('DZD','DZD','Algerian Dinar','د.ج.‏',2,0.0,'DZD','Algerian dinars');
INSERT INTO currency_map VALUES ('EGP','EGP','Egyptian Pound','ج.م.‏',2,0.0,'EGP','Egyptian pounds');
INSERT INTO currency_map VALUES ('ERN','ERN','Eritrean Nakfa','Nfk',2,0.0,'ERN','Eritrean nakfas');
INSERT INTO currency_map VALUES ('ETB','ETB','Ethiopian Birr','ብር',2,0.0,'ETB','Ethiopian birrs');
INSERT INTO currency_map VALUES ('EUR','€','Euro','€',2,0.0,'EUR','euros');
INSERT INTO currency_map VALUES ('GBP','£','British Pound Sterling','£',2,0.0,'GBP','British pounds sterling');
INSERT INTO currency_map VALUES ('GEL','GEL','Georgian Lari','GEL',2,0.0,'GEL','Georgian laris');
INSERT INTO currency_map VALUES ('GHS','GHS','Ghanaian Cedi','GHS',2,0.0,'GHS','Ghanaian cedis');
INSERT INTO currency_map VALUES ('GNF','GNF','Guinean Franc','FG',0,0.0,'GNF','Guinean francs');
INSERT INTO currency_map VALUES ('GTQ','GTQ','Guatemalan Quetzal','Q',2,0.0,'GTQ','Guatemalan quetzals');
INSERT INTO currency_map VALUES ('GYD','GYD','Guyanaese Dollar','GYD',0,0.0,'GYD','Guyanaese dollars');
INSERT INTO currency_map VALUES ('HKD','HK$','Hong Kong Dollar','$',2,0.0,'HKD','Hong Kong dollars');
INSERT INTO currency_map VALUES ('HNL','HNL','Honduran Lempira','L',2,0.0,'HNL','Honduran lempiras');
INSERT INTO currency_map VALUES ('HRK','HRK','Croatian Kuna','kn',2,0.0,'HRK','Croatian kunas');
INSERT INTO currency_map VALUES ('HUF','HUF','Hungarian Forint','Ft',0,0.0,'HUF','Hungarian forints');
INSERT INTO currency_map VALUES ('IDR','IDR','Indonesian Rupiah','Rp',0,0.0,'IDR','Indonesian rupiahs');
INSERT INTO currency_map VALUES ('ILS','₪','Israeli New Sheqel','₪',2,0.0,'ILS','Israeli new sheqels');
INSERT INTO currency_map VALUES ('INR','₹','Indian Rupee','₹',2,0.0,'INR','Indian rupees');
INSERT INTO currency_map VALUES ('IQD','IQD','Iraqi Dinar','د.ع.‏',0,0.0,'IQD','Iraqi dinars');
INSERT INTO currency_map VALUES ('IRR','IRR','Iranian Rial','﷼',0,0.0,'IRR','Iranian rials');
INSERT INTO currency_map VALUES ('ISK','ISK','Icelandic Króna','kr',0,0.0,'ISK','Icelandic krónur');
INSERT INTO currency_map VALUES ('JMD','JMD','Jamaican Dollar','$',2,0.0,'JMD','Jamaican dollars');
INSERT INTO currency_map VALUES ('JOD','JOD','Jordanian Dinar','د.أ.‏',3,0.0,'JOD','Jordanian dinars');
INSERT INTO currency_map VALUES ('JPY','¥','Japanese Yen','￥',0,0.0,'JPY','Japanese yen');
INSERT INTO currency_map VALUES ('KES','KES','Kenyan Shilling','Ksh',2,0.0,'KES','Kenyan shillings');
INSERT INTO currency_map VALUES ('KHR','KHR','Cambodian Riel','៛',2,0.0,'KHR','Cambodian riels');
INSERT INTO currency_map VALUES ('KMF','KMF','Comorian Franc','CF',0,0.0,'KMF','Comorian francs');
INSERT INTO currency_map VALUES ('KRW','₩','South Korean Won','₩',0,0.0,'KRW','South Korean won');
INSERT INTO currency_map VALUES ('KWD','KWD','Kuwaiti Dinar','د.ك.‏',3,0.0,'KWD','Kuwaiti dinars');
INSERT INTO currency_map VALUES ('KZT','KZT','Kazakhstani Tenge','₸',2,0.0,'KZT','Kazakhstani tenges');
INSERT INTO currency_map VALUES ('LBP','LBP','Lebanese Pound','ل.ل.‏',0,0.0,'LBP','Lebanese pounds');
INSERT INTO currency_map VALUES ('LKR','LKR','Sri Lankan Rupee','රු.',2,0.0,'LKR','Sri Lankan rupees');
INSERT INTO currency_map VALUES ('LRD','LRD','Liberian Dollar','$',2,0.0,'LRD','Liberian dollars');
INSERT INTO currency_map VALUES ('LTL','LTL','Lithuanian Litas','Lt',2,0.0,'LTL','Lithuanian litai');
INSERT INTO currency_map VALUES ('LVL','LVL','Latvian Lats','Ls',2,0.0,'LVL','Latvian lati');
INSERT INTO currency_map VALUES ('LYD','LYD','Libyan Dinar','د.ل.‏',3,0.0,'LYD','Libyan dinars');
INSERT INTO currency_map VALUES ('MAD','MAD','Moroccan Dirham','د.م.‏',2,0.0,'MAD','Moroccan dirhams');
INSERT INTO currency_map VALUES ('MDL','MDL','Moldovan Leu','MDL',2,0.0,'MDL','Moldovan lei');
INSERT INTO currency_map VALUES ('MGA','MGA','Malagasy Ariary','MGA',0,0.0,'MGA','Malagasy Ariaries');
INSERT INTO currency_map VALUES ('MKD','MKD','Macedonian Denar','MKD',2,0.0,'MKD','Macedonian denari');
INSERT INTO currency_map VALUES ('MMK','MMK','Myanma Kyat','K',0,0.0,'MMK','Myanma kyats');
INSERT INTO currency_map VALUES ('MOP','MOP','Macanese Pataca','MOP',2,0.0,'MOP','Macanese patacas');
INSERT INTO currency_map VALUES ('MUR','MUR','Mauritian Rupee','MUR',0,0.0,'MUR','Mauritian rupees');
INSERT INTO currency_map VALUES ('MXN','MX$','Mexican Peso','$',2,0.0,'MXN','Mexican pesos');
INSERT INTO currency_map VALUES ('MYR','MYR','Malaysian Ringgit','RM',2,0.0,'MYR','Malaysian ringgits');
INSERT INTO currency_map VALUES ('MZN','MZN','Mozambican Metical','MTn',2,0.0,'MZN','Mozambican meticals');
INSERT INTO currency_map VALUES ('NAD','NAD','Namibian Dollar','$',2,0.0,'NAD','Namibian dollars');
INSERT INTO currency_map VALUES ('NGN','NGN','Nigerian Naira','₦',2,0.0,'NGN','Nigerian nairas');
INSERT INTO currency_map VALUES ('NIO','NIO','Nicaraguan Córdoba','C$',2,0.0,'NIO','Nicaraguan córdobas');
INSERT INTO currency_map VALUES ('NOK','NOK','Norwegian Krone','kr',2,0.0,'NOK','Norwegian kroner');
INSERT INTO currency_map VALUES ('NPR','NPR','Nepalese Rupee','नेरू',2,0.0,'NPR','Nepalese rupees');
INSERT INTO currency_map VALUES ('NZD','NZ$','New Zealand Dollar','$',2,0.0,'NZD','New Zealand dollars');
INSERT INTO currency_map VALUES ('OMR','OMR','Omani Rial','ر.ع.‏',3,0.0,'OMR','Omani rials');
INSERT INTO currency_map VALUES ('PAB','PAB','Panamanian Balboa','B/.',2,0.0,'PAB','Panamanian balboas');
INSERT INTO currency_map VALUES ('PEN','PEN','Peruvian Nuevo Sol','S/.',2,0.0,'PEN','Peruvian nuevos soles');
INSERT INTO currency_map VALUES ('PHP','PHP','Philippine Peso','₱',2,0.0,'PHP','Philippine pesos');
INSERT INTO currency_map VALUES ('PKR','PKR','Pakistani Rupee','₨',0,0.0,'PKR','Pakistani rupees');
INSERT INTO currency_map VALUES ('PLN','PLN','Polish Zloty','zł',2,0.0,'PLN','Polish zlotys');
INSERT INTO currency_map VALUES ('PYG','PYG','Paraguayan Guarani','₲',0,0.0,'PYG','Paraguayan guaranis');
INSERT INTO currency_map VALUES ('QAR','QAR','Qatari Rial','ر.ق.‏',2,0.0,'QAR','Qatari rials');
INSERT INTO currency_map VALUES ('RON','RON','Romanian Leu','RON',2,0.0,'RON','Romanian lei');
INSERT INTO currency_map VALUES ('RSD','RSD','Serbian Dinar','дин.',0,0.0,'RSD','Serbian dinars');
INSERT INTO currency_map VALUES ('RUB','RUB','Russian Ruble','руб.',2,0.0,'RUB','Russian rubles');
INSERT INTO currency_map VALUES ('RWF','RWF','Rwandan Franc','FR',0,0.0,'RWF','Rwandan francs');
INSERT INTO currency_map VALUES ('SAR','SAR','Saudi Riyal','ر.س.‏',2,0.0,'SAR','Saudi riyals');
INSERT INTO currency_map VALUES ('SDG','SDG','Sudanese Pound','SDG',2,0.0,'SDG','Sudanese pounds');
INSERT INTO currency_map VALUES ('SEK','SEK','Swedish Krona','kr',2,0.0,'SEK','Swedish kronor');
INSERT INTO currency_map VALUES ('SGD','SGD','Singapore Dollar','$',2,0.0,'SGD','Singapore dollars');
INSERT INTO currency_map VALUES ('SOS','SOS','Somali Shilling','SOS',0,0.0,'SOS','Somali shillings');
INSERT INTO currency_map VALUES ('STD','STD','São Tomé and Príncipe Dobra','Db',0,0.0,'STD','São Tomé and Príncipe dobras');
INSERT INTO currency_map VALUES ('SYP','SYP','Syrian Pound','ل.س.‏',0,0.0,'SYP','Syrian pounds');
INSERT INTO currency_map VALUES ('THB','฿','Thai Baht','฿',2,0.0,'THB','Thai baht');
INSERT INTO currency_map VALUES ('TND','TND','Tunisian Dinar','د.ت.‏',3,0.0,'TND','Tunisian dinars');
INSERT INTO currency_map VALUES ('TOP','TOP','Tongan Paʻanga','T$',2,0.0,'TOP','Tongan paʻanga');
INSERT INTO currency_map VALUES ('TRY','TRY','Turkish Lira','TL',2,0.0,'TRY','Turkish Lira');
INSERT INTO currency_map VALUES ('TTD','TTD','Trinidad and Tobago Dollar','$',2,0.0,'TTD','Trinidad and Tobago dollars');
INSERT INTO currency_map VALUES ('TWD','NT$','New Taiwan Dollar','NT$',2,0.0,'TWD','New Taiwan dollars');
INSERT INTO currency_map VALUES ('TZS','TZS','Tanzanian Shilling','TSh',0,0.0,'TZS','Tanzanian shillings');
INSERT INTO currency_map VALUES ('UAH','UAH','Ukrainian Hryvnia','₴',2,0.0,'UAH','Ukrainian hryvnias');
INSERT INTO currency_map VALUES ('UGX','UGX','Ugandan Shilling','USh',0,0.0,'UGX','Ugandan shillings');
INSERT INTO currency_map VALUES ('USD','$','US Dollar','$',2,0.0,'USD','US dollars');
INSERT INTO currency_map VALUES ('UYU','UYU','Uruguayan Peso','$',2,0.0,'UYU','Uruguayan pesos');
INSERT INTO currency_map VALUES ('UZS','UZS','Uzbekistan Som','UZS',0,0.0,'UZS','Uzbekistan som');
INSERT INTO currency_map VALUES ('VEF','VEF','Venezuelan Bolívar','Bs.F.',2,0.0,'VEF','Venezuelan bolívars');
INSERT INTO currency_map VALUES ('VND','₫','Vietnamese Dong','₫',0,0.0,'VND','Vietnamese dong');
INSERT INTO currency_map VALUES ('XAF','FCFA','CFA Franc BEAC','FCFA',0,0.0,'XAF','CFA francs BEAC');
INSERT INTO currency_map VALUES ('XOF','CFA','CFA Franc BCEAO','CFA',0,0.0,'XOF','CFA francs BCEAO');
INSERT INTO currency_map VALUES ('YER','YER','Yemeni Rial','ر.ي.‏',0,0.0,'YER','Yemeni rials');
INSERT INTO currency_map VALUES ('ZAR','ZAR','South African Rand','R',2,0.0,'ZAR','South African rand');
INSERT INTO currency_map VALUES ('ZMK','ZMK','Zambian Kwacha','ZK',0,0.0,'ZMK','Zambian kwachas');
